from __future__ import annotations

import os
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta

import pytest
from sqlalchemy import Engine, create_engine, text

from app.application.ports import TikTokActivationError
from app.core.config import RuntimeMode
from app.core.write_policy import WritePolicy
from app.infrastructure.persistence.social_v2.tiktok_activation import (
    ProjectionTikTokActivationStore,
)

DATABASE_URL = os.getenv("TEST_POSTGRES_URL")
pytestmark = pytest.mark.skipif(not DATABASE_URL, reason="TEST_POSTGRES_URL is not configured")
NOW = datetime(2026, 8, 27, 12, tzinfo=UTC)


@pytest.fixture()
def store() -> Iterator[ProjectionTikTokActivationStore]:
    assert DATABASE_URL
    engine = create_engine(DATABASE_URL)
    _drop(engine)
    with engine.begin() as connection:
        for statement in _schema():
            connection.execute(text(statement))
        connection.execute(
            text(
                """INSERT INTO brands (id, tenant_id, name)
                   VALUES (101, 1, 'First Brand'), (102, 1, 'Second Brand')"""
            )
        )
    policy = WritePolicy(runtime_mode=RuntimeMode.DEVELOPMENT, writes_enabled=True)
    yield ProjectionTikTokActivationStore(engine, policy)
    _drop(engine)
    engine.dispose()


def test_tiktok_account_cannot_be_pending_for_two_brands(
    store: ProjectionTikTokActivationStore,
) -> None:
    first = store.create_pending(
        brand_id=101,
        business_id="creator-1",
        credential_reference="credential-first",
        access_expires_at=NOW + timedelta(days=1),
    )
    same_brand = store.create_pending(
        brand_id=101,
        business_id="creator-1",
        credential_reference="credential-refreshed",
        access_expires_at=NOW + timedelta(days=1),
    )

    assert same_brand.connection_id == first.connection_id
    assert same_brand.link_id == first.link_id
    with pytest.raises(
        TikTokActivationError,
        match="^activation_link_already_connected_elsewhere$",
    ):
        store.create_pending(
            brand_id=102,
            business_id="creator-1",
            credential_reference="credential-wrong-brand",
            access_expires_at=NOW + timedelta(days=1),
        )

    with store.engine.connect() as connection:
        assert connection.execute(
            text(
                """SELECT count(*) FROM linked_social_accounts
                   WHERE platform='tiktok' AND external_id='creator-1'
                     AND status='pending_verification'"""
            )
        ).scalar_one() == 1
        assert connection.execute(
            text(
                """SELECT count(*) FROM platform_connections
                   WHERE brand_id=102 AND platform='tiktok'"""
            )
        ).scalar_one() == 0

    disconnected = store.disconnect(brand_id=101, business_id="creator-1")
    assert disconnected is not None
    assert disconnected.state == "disconnected"
    with store.engine.connect() as connection:
        projection = connection.execute(
            text(
                """SELECT status, payload_json->>'state'
                   FROM social_projection_state
                   WHERE projection_key=:key"""
            ),
            {"key": f"v2:tiktok:connection-credential:{first.connection_id}"},
        ).one()
        assert projection == ("inactive", "disconnected")
    transferred = store.create_pending(
        brand_id=102,
        business_id="creator-1",
        credential_reference="credential-second",
        access_expires_at=NOW + timedelta(days=1),
    )
    assert transferred.brand_id == 102
    assert transferred.state == "pending_verification"


def _drop(engine: Engine) -> None:
    with engine.begin() as connection:
        for table_name in (
            "social_projection_state",
            "linked_social_accounts",
            "assets",
            "platform_connections",
            "brands",
            "tenants",
        ):
            connection.execute(text(f"DROP TABLE IF EXISTS {table_name} CASCADE"))


def _schema() -> tuple[str, ...]:
    return (
        "CREATE TABLE tenants (id bigint PRIMARY KEY, name varchar(255) NOT NULL)",
        """CREATE TABLE brands (
               id bigint PRIMARY KEY,
               tenant_id bigint NOT NULL REFERENCES tenants(id),
               name varchar(255)
           )""",
        "INSERT INTO tenants (id, name) VALUES (1, 'Test Tenant')",
        """CREATE TABLE platform_connections (
               id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               tenant_id bigint NOT NULL REFERENCES tenants(id),
               brand_id bigint NOT NULL REFERENCES brands(id),
               platform varchar(32) NOT NULL,
               status varchar(64) NOT NULL,
               expires_at timestamptz,
               projected_at timestamptz,
               projection_source varchar(64) NOT NULL,
               updated_at timestamptz NOT NULL DEFAULT now()
           )""",
        """CREATE TABLE assets (
               id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               brand_id bigint NOT NULL REFERENCES brands(id),
               platform varchar(32) NOT NULL,
               external_id varchar(255) NOT NULL,
               display_name varchar(255) NOT NULL DEFAULT '',
               status varchar(64) NOT NULL DEFAULT 'active',
               updated_at timestamptz NOT NULL DEFAULT now()
           )""",
        """CREATE TABLE linked_social_accounts (
               id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               brand_id bigint NOT NULL REFERENCES brands(id),
               platform varchar(32) NOT NULL,
               external_id varchar(255) NOT NULL,
               display_name varchar(255) NOT NULL DEFAULT '',
               connection_id bigint REFERENCES platform_connections(id),
               asset_id bigint REFERENCES assets(id),
               status varchar(64) NOT NULL,
               health_status varchar(64) NOT NULL,
               backfill_status varchar(64) NOT NULL,
               nightly_enabled boolean NOT NULL,
               created_at timestamptz NOT NULL DEFAULT now(),
               updated_at timestamptz NOT NULL DEFAULT now(),
               UNIQUE (brand_id, platform, external_id)
           )""",
        """CREATE TABLE social_projection_state (
               projection_key varchar(255) PRIMARY KEY,
               status varchar(32) NOT NULL DEFAULT 'active',
               payload_json jsonb NOT NULL,
               updated_at timestamptz NOT NULL DEFAULT now()
           )""",
    )
