-- Social Media V2 owns every object in this schema. No live V1 database is referenced.

CREATE TABLE IF NOT EXISTS tenants (
    id bigint PRIMARY KEY,
    name varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO tenants (id, name) VALUES (1, 'Social Media V2')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS brands (
    id bigint PRIMARY KEY,
    tenant_id bigint NOT NULL DEFAULT 1 REFERENCES tenants(id),
    name varchar(255),
    parent_brand_id bigint REFERENCES brands(id),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS social_projection_state (
    projection_key varchar(255) PRIMARY KEY,
    brand_id bigint REFERENCES brands(id),
    status varchar(32) NOT NULL DEFAULT 'active',
    projection_source varchar(64) NOT NULL DEFAULT 'social_media_v2',
    projected_at timestamptz,
    payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_social_projection_state_brand
ON social_projection_state (brand_id);

CREATE TABLE IF NOT EXISTS meta_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform varchar(32) NOT NULL,
    asset_type varchar(32) NOT NULL,
    external_id varchar(255) NOT NULL,
    display_name varchar(255),
    status varchar(32) NOT NULL DEFAULT 'active',
    last_discovered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_meta_accounts_platform_external UNIQUE (platform, external_id)
);

CREATE TABLE IF NOT EXISTS platform_connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL DEFAULT 1 REFERENCES tenants(id),
    brand_id bigint NOT NULL REFERENCES brands(id),
    platform varchar(32) NOT NULL,
    status varchar(64) NOT NULL,
    expires_at timestamptz,
    projected_at timestamptz,
    projection_source varchar(64) NOT NULL DEFAULT 'social_media_v2',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_platform_connections_brand_platform
ON platform_connections (brand_id, platform);

CREATE TABLE IF NOT EXISTS assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL DEFAULT 1 REFERENCES tenants(id),
    brand_id bigint NOT NULL REFERENCES brands(id),
    platform varchar(32) NOT NULL,
    asset_type varchar(32) NOT NULL DEFAULT 'account',
    external_id varchar(255) NOT NULL,
    display_name varchar(255) NOT NULL DEFAULT '',
    meta_account_id bigint REFERENCES meta_accounts(id),
    status varchar(64) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_assets_brand_platform_external UNIQUE (brand_id, platform, external_id)
);

CREATE TABLE IF NOT EXISTS brand_social_account_discoveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id bigint NOT NULL REFERENCES brands(id),
    connection_id bigint NOT NULL REFERENCES platform_connections(id),
    meta_account_id bigint NOT NULL REFERENCES meta_accounts(id),
    platform varchar(32) NOT NULL,
    external_id varchar(255) NOT NULL,
    display_name varchar(255),
    status varchar(32) NOT NULL DEFAULT 'discovered',
    last_discovered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_brand_social_discovery UNIQUE (brand_id, platform, external_id)
);

CREATE TABLE IF NOT EXISTS linked_social_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id bigint NOT NULL REFERENCES brands(id),
    platform varchar(32) NOT NULL,
    external_id varchar(255) NOT NULL,
    display_name varchar(255) NOT NULL DEFAULT '',
    connection_id bigint REFERENCES platform_connections(id),
    meta_account_id bigint REFERENCES meta_accounts(id),
    asset_id bigint REFERENCES assets(id),
    status varchar(64) NOT NULL DEFAULT 'pending_verification',
    health_status varchar(64) NOT NULL DEFAULT 'unknown',
    backfill_status varchar(64) NOT NULL DEFAULT 'pending',
    nightly_enabled boolean NOT NULL DEFAULT false,
    last_synced_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_linked_social_accounts_brand_platform_external
        UNIQUE (brand_id, platform, external_id)
);

CREATE TABLE IF NOT EXISTS asset_sync_state (
    asset_id bigint PRIMARY KEY REFERENCES assets(id) ON DELETE CASCADE,
    last_synced_at timestamptz,
    last_error varchar(1024),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS metrics_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    brand_id bigint NOT NULL REFERENCES brands(id),
    date date NOT NULL,
    metric_id varchar(64) NOT NULL,
    value_numeric double precision NOT NULL,
    breakdown_key varchar(64),
    breakdown_value varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id, date)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_metrics_daily_account_rows
ON metrics_daily (asset_id, date, metric_id)
WHERE breakdown_key IS NULL AND breakdown_value IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_metrics_daily_breakdown_rows
ON metrics_daily (asset_id, date, metric_id, breakdown_key, breakdown_value)
WHERE breakdown_key IS NOT NULL AND breakdown_value IS NOT NULL;

CREATE TABLE IF NOT EXISTS content_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    brand_id bigint NOT NULL REFERENCES brands(id),
    content_id varchar(128) NOT NULL,
    content_type varchar(32) NOT NULL DEFAULT '',
    permalink varchar(512) NOT NULL DEFAULT '',
    message varchar(4096) NOT NULL DEFAULT '',
    media_url varchar(2048) NOT NULL DEFAULT '',
    created_time timestamptz,
    likes_count integer NOT NULL DEFAULT 0,
    comments_count integer NOT NULL DEFAULT 0,
    shares_count integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_content_items_asset_content UNIQUE (asset_id, content_id)
);

CREATE TABLE IF NOT EXISTS content_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    content_id varchar(255) NOT NULL,
    platform varchar(32) NOT NULL,
    comment_id varchar(255) NOT NULL,
    user_id varchar(255),
    user_name varchar(255),
    text text NOT NULL DEFAULT '',
    like_count integer NOT NULL DEFAULT 0,
    reply_count integer NOT NULL DEFAULT 0,
    answered boolean NOT NULL DEFAULT false,
    attachment_type varchar(64),
    attachment_media_type varchar(64),
    attachment_url varchar(2048),
    commented_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_content_comments_asset_comment UNIQUE (asset_id, comment_id)
);

CREATE TABLE IF NOT EXISTS media_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id bigint NOT NULL REFERENCES brands(id),
    asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    content_id varchar(128) NOT NULL,
    platform varchar(32) NOT NULL,
    media_kind varchar(32) NOT NULL,
    storage_path varchar(1024) NOT NULL,
    source_url varchar(2048) NOT NULL,
    source_status integer,
    mime_type varchar(128) NOT NULL,
    size_bytes bigint NOT NULL,
    checksum varchar(64) NOT NULL,
    last_verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_media_assets_asset_content_kind
        UNIQUE (asset_id, content_id, media_kind)
);

CREATE TABLE IF NOT EXISTS social_backfill_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id bigint NOT NULL REFERENCES brands(id),
    asset_id bigint REFERENCES assets(id) ON DELETE CASCADE,
    platform varchar(32) NOT NULL,
    stage varchar(64) NOT NULL,
    status varchar(32) NOT NULL,
    scheduled_for timestamptz NOT NULL,
    started_at timestamptz,
    finished_at timestamptz,
    error_code varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS brand_ai_insights (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id bigint NOT NULL REFERENCES brands(id),
    status varchar(32) NOT NULL,
    date_from date,
    date_to date,
    strategic_summary text,
    action_recommendations text,
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz
);
