/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Me */
        get: operations["auth_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/facebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_dashboards_facebook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/instagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_dashboards_instagram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_dashboards_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/tiktok": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_dashboards_tiktok_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health probe */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights_api_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/instagram/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instagram Media */
        get: operations["instagram_media_api_media_instagram__content_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backfill */
        post: operations["backfill_api_operations_backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dormant readiness probe */
        get: operations["readiness_api_operations_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_operations_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/facebook/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_platforms_facebook_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/instagram/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_platforms_instagram_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/tiktok/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_platforms_tiktok_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_settings_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/brand-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brand Links */
        get: operations["brand_links_api_settings_brand_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brands */
        get: operations["brands_api_settings_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connections */
        get: operations["connections_api_settings_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/social-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Accounts */
        get: operations["social_accounts_api_settings_social_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/sync-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Jobs */
        get: operations["sync_jobs_api_settings_sync_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/tiktok/activation-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiktok Activation Readiness */
        get: operations["tiktok_activation_readiness_api_settings_tiktok_activation_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/tiktok/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiktok Connection */
        get: operations["tiktok_connection_api_settings_tiktok_connection_get"];
        put?: never;
        post?: never;
        /** Delete Tiktok Connection */
        delete: operations["delete_tiktok_connection_api_settings_tiktok_connection_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Brands */
        get: operations["workspace_brands_api_workspace_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Capabilities */
        get: operations["workspace_capabilities_api_workspace_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/provisioning/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provisioning Event */
        post: operations["provisioning_event_internal_provisioning_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditResponse */
        AuditResponse: {
            /** Items */
            items: unknown[];
            meta: components["schemas"]["BrandScope"];
            /** Reason */
            reason: string;
            /** Status */
            status: string;
        };
        /** AuthMeResponse */
        AuthMeResponse: {
            /** Access Mode */
            access_mode: string;
            /** Authenticated */
            authenticated: boolean;
            /** Brand Id */
            brand_id: string;
            /** Email */
            email: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Is Internal Staff */
            is_internal_staff: boolean;
            /** Revoked */
            revoked: boolean;
            /** Role */
            role: string;
            /** Settings Visible */
            settings_visible: boolean;
            /** Source System */
            source_system: string | null;
            /** User Id */
            user_id: string;
        };
        /** BrandFamilyProjection */
        BrandFamilyProjection: {
            /** Brand Ids */
            brand_ids: string[];
            /** Root Brand Id */
            root_brand_id: string;
        };
        /** BrandLinkItem */
        BrandLinkItem: {
            /** Account Id */
            account_id: number;
            /** Brand Id */
            brand_id: string;
            /** Display Name */
            display_name: string;
            /** External Id */
            external_id: string;
            /** Link Status */
            link_status: string;
            platform: components["schemas"]["PlatformId"];
        };
        /** BrandLinksResponse */
        BrandLinksResponse: {
            /** Items */
            items: components["schemas"]["BrandLinkItem"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** BrandScope */
        BrandScope: {
            /** Requested Brand Id */
            requested_brand_id: string;
            /** Resolved Brand Ids */
            resolved_brand_ids: string[];
            /** Rollup */
            rollup: boolean;
        };
        /** BrandWorkspace */
        BrandWorkspace: {
            /** Brands */
            brands: components["schemas"]["WorkspaceBrand"][];
            /** Default Brand Id */
            default_brand_id: string;
            /** Families */
            families: components["schemas"]["BrandFamilyProjection"][];
            scope: components["schemas"]["BrandScope"];
        };
        /**
         * CapabilityId
         * @enum {string}
         */
        CapabilityId: "profile" | "content" | "comments" | "audience";
        /** CapabilityPlatform */
        CapabilityPlatform: {
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityRecord"][];
            /** Linked Account Count */
            linked_account_count: number;
            /** Navigation Available */
            navigation_available: boolean;
            platform: components["schemas"]["PlatformId"];
        };
        /** CapabilityRecord */
        CapabilityRecord: {
            capability: components["schemas"]["CapabilityId"];
            platform: components["schemas"]["PlatformId"];
            /** Reason */
            reason: string;
            status: components["schemas"]["CapabilityStatus"];
        };
        /**
         * CapabilityStatus
         * @enum {string}
         */
        CapabilityStatus: "unsupported" | "not_approved" | "not_configured" | "blocked_configuration" | "manual_activation_required" | "partial" | "available";
        /** CommunitySummary */
        CommunitySummary: {
            /** Answered Comments */
            answered_comments: number;
            /** Comment Likes */
            comment_likes: number;
            data_status: components["schemas"]["DataStatus"];
            /** Total Comments */
            total_comments: number;
            /** Unanswered Comments */
            unanswered_comments: number;
        };
        /** ConnectionsResponse */
        ConnectionsResponse: {
            /** Items */
            items: components["schemas"]["ReportingConnection"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** DashboardBreakdown */
        DashboardBreakdown: {
            /** Dimension */
            dimension: string;
            /** Items */
            items: components["schemas"]["DashboardBreakdownItem"][];
            metric_id: components["schemas"]["MetricId"];
        };
        /** DashboardBreakdownItem */
        DashboardBreakdownItem: {
            /** Key */
            key: string;
            /** Percentage */
            percentage: number | null;
            /** Value */
            value: number;
        };
        /** DashboardContent */
        DashboardContent: {
            /** Account Id */
            account_id: number;
            /** Comments Count */
            comments_count: number;
            /** Content Type */
            content_type: string;
            /** External Content Id */
            external_content_id: string;
            /** Interactions */
            interactions: number;
            /** Likes Count */
            likes_count: number;
            /** Media Url */
            media_url: string;
            /** Message */
            message: string;
            /** Permalink */
            permalink: string;
            /** Published At */
            published_at: string | null;
            /** Shares Count */
            shares_count: number;
        };
        /** DashboardMeta */
        DashboardMeta: {
            /** Dashboard Id */
            dashboard_id: string;
            data_status: components["schemas"]["DataStatus"];
            date_range: components["schemas"]["ReportingRange"];
            /** Expected Days */
            expected_days: number;
            freshness: components["schemas"]["FreshnessStatus"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Observed Days */
            observed_days: number;
            platform: components["schemas"]["PlatformId"] | null;
            /** Requested Brand Id */
            requested_brand_id: string;
            /** Resolved Account Ids */
            resolved_account_ids: number[];
            /** Resolved Brand Ids */
            resolved_brand_ids: string[];
            /** Rollup */
            rollup: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** DashboardMetric */
        DashboardMetric: {
            data_status: components["schemas"]["DataStatus"];
            /** Delta Pct */
            delta_pct: number | null;
            metric_id: components["schemas"]["MetricId"];
            /** Previous Value */
            previous_value: number | null;
            semantic_type: components["schemas"]["SemanticType"];
            unit: components["schemas"]["Unit"];
            /** Value */
            value: number | null;
        };
        /** DashboardPoint */
        DashboardPoint: {
            /**
             * Observed On
             * Format: date
             */
            observed_on: string;
            /** Value */
            value: number;
        };
        /** DashboardSeries */
        DashboardSeries: {
            metric_id: components["schemas"]["MetricId"];
            /** Points */
            points: components["schemas"]["DashboardPoint"][];
            semantic_type: components["schemas"]["SemanticType"];
        };
        /**
         * DataStatus
         * @enum {string}
         */
        DataStatus: "available" | "partial" | "unavailable";
        /**
         * FreshnessStatus
         * @enum {string}
         */
        FreshnessStatus: "fresh" | "stale" | "outdated" | "never_synced";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Items */
            items: components["schemas"]["ReportingInsight"][];
            meta: components["schemas"]["BrandScope"];
        };
        /**
         * MetricId
         * @enum {string}
         */
        MetricId: "followers" | "following" | "new_followers" | "reach" | "reach_paid" | "reach_organic" | "views" | "views_paid" | "views_organic" | "interactions" | "page_views" | "profile_views" | "website_clicks" | "total_actions" | "reactions" | "media_count" | "video_views_total" | "video_views_change" | "video_likes_total" | "video_comments_total" | "video_shares_total" | "video_engagements_total" | "video_engagement_rate";
        /** OperationsReadinessResponse */
        OperationsReadinessResponse: {
            /** Database Configured */
            database_configured: boolean;
            /**
             * Platforms
             * @default []
             */
            platforms: components["schemas"]["ReadinessPlatform"][];
            runtime_mode: components["schemas"]["RuntimeMode"];
            scope?: components["schemas"]["BrandScope"] | null;
            /** Status */
            status: string;
            /** Writes Enabled */
            writes_enabled: boolean;
        };
        /** OverviewDashboard */
        OverviewDashboard: {
            community: components["schemas"]["CommunitySummary"];
            /** Content */
            content: components["schemas"]["DashboardContent"][];
            meta: components["schemas"]["DashboardMeta"];
            /** Metrics */
            metrics: components["schemas"]["DashboardMetric"][];
            /** Platforms */
            platforms: components["schemas"]["PlatformDashboard"][];
        };
        /** PlatformAccountsResponse */
        PlatformAccountsResponse: {
            /** Accounts */
            accounts: components["schemas"]["ReportingAccount"][];
            meta: components["schemas"]["BrandScope"];
            platform: components["schemas"]["PlatformId"];
        };
        /** PlatformDashboard */
        PlatformDashboard: {
            /** Breakdowns */
            breakdowns: components["schemas"]["DashboardBreakdown"][];
            community: components["schemas"]["CommunitySummary"];
            /** Content */
            content: components["schemas"]["DashboardContent"][];
            meta: components["schemas"]["DashboardMeta"];
            /** Metrics */
            metrics: components["schemas"]["DashboardMetric"][];
            /** Series */
            series: components["schemas"]["DashboardSeries"][];
        };
        /**
         * PlatformId
         * @enum {string}
         */
        PlatformId: "facebook" | "instagram" | "tiktok";
        /** ReadinessPlatform */
        ReadinessPlatform: {
            /** Account Count */
            account_count: number;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Pending Job Count */
            pending_job_count: number;
            platform: components["schemas"]["PlatformId"];
        };
        /** ReportingAccount */
        ReportingAccount: {
            /** Account Id */
            account_id: number;
            /** Backfill Status */
            backfill_status: string;
            /** Brand Id */
            brand_id: string;
            /** Connection State */
            connection_state: string;
            /** Display Name */
            display_name: string;
            /** External Id */
            external_id: string;
            /** Health Status */
            health_status: string;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Nightly Enabled */
            nightly_enabled: boolean;
            platform: components["schemas"]["PlatformId"];
            /** Status */
            status: string;
        };
        /** ReportingConnection */
        ReportingConnection: {
            /** Brand Id */
            brand_id: string;
            /** Connection Id */
            connection_id: number;
            /** Expires At */
            expires_at: string | null;
            platform: components["schemas"]["PlatformId"];
            /** Projected At */
            projected_at: string | null;
            /** State */
            state: string;
        };
        /** ReportingInsight */
        ReportingInsight: {
            /** Brand Id */
            brand_id: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Insight Id */
            insight_id: number;
            /** Recommendations */
            recommendations: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary: string | null;
        };
        /** ReportingRange */
        ReportingRange: {
            /**
             * End On
             * Format: date
             */
            end_on: string;
            /** Key */
            key: string;
            /**
             * Start On
             * Format: date
             */
            start_on: string;
        };
        /** ReportingSyncJob */
        ReportingSyncJob: {
            /** Account Id */
            account_id: number | null;
            /** Brand Id */
            brand_id: string;
            /** Error Code */
            error_code: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Job Id */
            job_id: number;
            platform: components["schemas"]["PlatformId"];
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** RuntimeCapabilities */
        RuntimeCapabilities: {
            /** Automated Schedule Available */
            automated_schedule_available: boolean;
            mode: components["schemas"]["RuntimeMode"];
            /** Writes Enabled */
            writes_enabled: boolean;
        };
        /**
         * RuntimeMode
         * @enum {string}
         */
        RuntimeMode: "development" | "dormant" | "cutover_read_only" | "cutover_credential_migration" | "cutover_canary" | "cutover_control_plane_drain" | "cutover_activation" | "active";
        /**
         * SemanticType
         * @enum {string}
         */
        SemanticType: "snapshot" | "flow" | "cumulative" | "ratio";
        /** SettingsBrandItem */
        SettingsBrandItem: {
            /** Access Mode */
            access_mode: string | null;
            /** Brand Id */
            brand_id: string;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Linked Account Count */
            linked_account_count: number;
            /** Name */
            name: string | null;
            /** Parent Brand Id */
            parent_brand_id: string | null;
            /** Role */
            role: string | null;
            /** Visibility */
            visibility: string;
        };
        /** SettingsBrandsResponse */
        SettingsBrandsResponse: {
            /** Items */
            items: components["schemas"]["SettingsBrandItem"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** SocialAccountsResponse */
        SocialAccountsResponse: {
            /** Items */
            items: components["schemas"]["ReportingAccount"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** SyncJobsResponse */
        SyncJobsResponse: {
            /** Items */
            items: components["schemas"]["ReportingSyncJob"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** TikTokActivationReadinessResponse */
        TikTokActivationReadinessResponse: {
            /** Brand Id */
            brand_id: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Connection State */
            connection_state: string;
            /**
             * Fresh Until
             * Format: date-time
             */
            fresh_until: string;
            /** Handoff Ready */
            handoff_ready: boolean;
            /** Launch Target */
            launch_target: string;
            /** Oauth Start Available */
            oauth_start_available: boolean;
            /** Reason */
            reason: string;
            runtime_mode: components["schemas"]["RuntimeMode"];
            /** Writes Enabled */
            writes_enabled: boolean;
        };
        /** TikTokConnectionResponse */
        TikTokConnectionResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityRecord"][];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            connection: components["schemas"]["ReportingConnection"] | null;
            meta: components["schemas"]["BrandScope"];
            /** State */
            state: string;
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "count" | "ratio";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceBrand */
        WorkspaceBrand: {
            /** Access Mode */
            access_mode: ("read" | "write") | null;
            /** Brand Id */
            brand_id: string;
            /** Name */
            name: string | null;
            /** Parent Brand Id */
            parent_brand_id: string | null;
            /** Role */
            role: string | null;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "active" | "hidden_parent";
        };
        /** WorkspaceCapabilitiesResponse */
        WorkspaceCapabilitiesResponse: {
            permissions: components["schemas"]["WorkspacePermissions"];
            /** Platforms */
            platforms: components["schemas"]["CapabilityPlatform"][];
            runtime: components["schemas"]["RuntimeCapabilities"];
            scope: components["schemas"]["BrandScope"];
        };
        /** WorkspacePermissions */
        WorkspacePermissions: {
            /** Internal Audit Visible */
            internal_audit_visible: boolean;
            /** Operation Mutation Available */
            operation_mutation_available: boolean;
            /** Rollup Available */
            rollup_available: boolean;
            /** Settings Visible */
            settings_visible: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_dashboards_facebook_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                range?: string;
                start_date?: string | null;
                end_date?: string | null;
                account_id?: number | null;
                content_type?: string | null;
                tab?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_dashboards_instagram_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                range?: string;
                start_date?: string | null;
                end_date?: string | null;
                account_id?: number | null;
                content_type?: string | null;
                tab?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_dashboards_overview_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                range?: string;
                start_date?: string | null;
                end_date?: string | null;
                content_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_dashboards_tiktok_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                range?: string;
                start_date?: string | null;
                end_date?: string | null;
                account_id?: number | null;
                content_type?: string | null;
                tab?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    insights_api_insights_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instagram_media_api_media_instagram__content_id__get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                account_id?: number | null;
            };
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backfill_api_operations_backfill_post: {
        parameters: {
            query: {
                platform: components["schemas"]["PlatformId"];
                account_id: number;
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Successful Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_api_operations_readiness_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_operations_sync_post: {
        parameters: {
            query: {
                platform: components["schemas"]["PlatformId"];
                account_id: number;
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Successful Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    endpoint_api_platforms_facebook_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_platforms_instagram_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_platforms_tiktok_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_settings_audit_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_links_api_settings_brand_links_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandLinksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brands_api_settings_brands_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBrandsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connections_api_settings_connections_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_accounts_api_settings_social_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                platform?: components["schemas"]["PlatformId"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_jobs_api_settings_sync_jobs_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiktok_activation_readiness_api_settings_tiktok_activation_readiness_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TikTokActivationReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiktok_connection_api_settings_tiktok_connection_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TikTokConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tiktok_connection_api_settings_tiktok_connection_delete: {
        parameters: {
            query?: {
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Successful Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    workspace_brands_api_workspace_brands_get: {
        parameters: {
            query?: {
                selected_brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandWorkspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_capabilities_api_workspace_capabilities_get: {
        parameters: {
            query?: {
                selected_brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceCapabilitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provisioning_event_internal_provisioning_events_post: {
        parameters: {
            query?: never;
            header: {
                "X-Accumulate-Timestamp": string;
                "X-Accumulate-Nonce": string;
                "X-Accumulate-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
