/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Me */
        get: operations["auth_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/facebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_dashboards_facebook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/instagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_dashboards_instagram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_dashboards_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboards/tiktok": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_dashboards_tiktok_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health probe */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights_api_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/meta/accounts/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Meta Link Accounts */
        post: operations["meta_link_accounts_api_integrations_meta_accounts_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/meta/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Meta Self Service Start */
        post: operations["meta_self_service_start_api_integrations_meta_oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/meta/self-service/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta Self Service Readiness */
        get: operations["meta_self_service_readiness_api_integrations_meta_self_service_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/status/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration Connections */
        get: operations["integration_connections_api_integrations_status_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/status/social-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration Social Accounts */
        get: operations["integration_social_accounts_api_integrations_status_social_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/status/sync-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration Sync Jobs */
        get: operations["integration_sync_jobs_api_integrations_status_sync_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/tiktok/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tiktok Self Service Start */
        post: operations["tiktok_self_service_start_api_integrations_tiktok_oauth_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/tiktok/self-service/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiktok Self Service Readiness */
        get: operations["tiktok_self_service_readiness_api_integrations_tiktok_self_service_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{platform}/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Media */
        get: operations["social_media_api_media__platform___content_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backfill */
        post: operations["backfill_api_operations_backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dormant readiness probe */
        get: operations["readiness_api_operations_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_operations_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/facebook/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_platforms_facebook_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/instagram/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_platforms_instagram_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms/tiktok/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint */
        get: operations["endpoint_api_platforms_tiktok_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_settings_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/brand-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brand Links */
        get: operations["brand_links_api_settings_brand_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brands */
        get: operations["brands_api_settings_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connections */
        get: operations["connections_api_settings_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/social-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Social Accounts */
        get: operations["social_accounts_api_settings_social_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/sync-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Jobs */
        get: operations["sync_jobs_api_settings_sync_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/tiktok/activation-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiktok Activation Readiness */
        get: operations["tiktok_activation_readiness_api_settings_tiktok_activation_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/tiktok/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiktok Connection */
        get: operations["tiktok_connection_api_settings_tiktok_connection_get"];
        put?: never;
        post?: never;
        /** Delete Tiktok Connection */
        delete: operations["delete_tiktok_connection_api_settings_tiktok_connection_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/tiktok/oauth/account/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tiktok Activation Start */
        post: operations["tiktok_activation_start_api_settings_tiktok_oauth_account_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social/meta/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta Activation Callback */
        get: operations["meta_activation_callback_api_social_meta_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/social/tiktok/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiktok Activation Callback */
        get: operations["tiktok_activation_callback_api_social_tiktok_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Brands */
        get: operations["workspace_brands_api_workspace_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Capabilities */
        get: operations["workspace_capabilities_api_workspace_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditResponse */
        AuditResponse: {
            /** Items */
            items: unknown[];
            meta: components["schemas"]["BrandScope"];
            /** Reason */
            reason: string;
            /** Status */
            status: string;
        };
        /** AuthMeResponse */
        AuthMeResponse: {
            /** Access Mode */
            access_mode: string;
            /** App Role */
            app_role: string | null;
            /** Authenticated */
            authenticated: boolean;
            /** Brand Id */
            brand_id: string;
            /** Email */
            email: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Integrations Visible */
            integrations_visible: boolean;
            /** Is Internal Staff */
            is_internal_staff: boolean;
            /** Revoked */
            revoked: boolean;
            /** Role */
            role: string;
            /** Settings Visible */
            settings_visible: boolean;
            /** Source System */
            source_system: string | null;
            /** User Id */
            user_id: string;
        };
        /**
         * AvailabilityStatus
         * @enum {string}
         */
        AvailabilityStatus: "available" | "partial" | "pending" | "provider_unavailable" | "unavailable";
        /** BrandFamilyProjection */
        BrandFamilyProjection: {
            /** Brand Ids */
            brand_ids: string[];
            /** Root Brand Id */
            root_brand_id: string;
        };
        /** BrandLinkItem */
        BrandLinkItem: {
            /** Account Id */
            account_id: number;
            /** Brand Id */
            brand_id: string;
            /** Display Name */
            display_name: string;
            /** External Id */
            external_id: string;
            /** Link Status */
            link_status: string;
            platform: components["schemas"]["PlatformId"];
        };
        /** BrandLinksResponse */
        BrandLinksResponse: {
            /** Items */
            items: components["schemas"]["BrandLinkItem"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** BrandScope */
        BrandScope: {
            /** Requested Brand Id */
            requested_brand_id: string;
            /** Resolved Brand Ids */
            resolved_brand_ids: string[];
            /** Rollup */
            rollup: boolean;
        };
        /** BrandWorkspace */
        BrandWorkspace: {
            /** Brands */
            brands: components["schemas"]["WorkspaceBrand"][];
            /** Default Brand Id */
            default_brand_id: string;
            /** Families */
            families: components["schemas"]["BrandFamilyProjection"][];
            scope: components["schemas"]["BrandScope"];
        };
        /**
         * CapabilityId
         * @enum {string}
         */
        CapabilityId: "profile" | "content" | "comments" | "audience";
        /** CapabilityPlatform */
        CapabilityPlatform: {
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityRecord"][];
            /** Linked Account Count */
            linked_account_count: number;
            /** Navigation Available */
            navigation_available: boolean;
            platform: components["schemas"]["PlatformId"];
        };
        /** CapabilityRecord */
        CapabilityRecord: {
            capability: components["schemas"]["CapabilityId"];
            platform: components["schemas"]["PlatformId"];
            /** Reason */
            reason: string;
            status: components["schemas"]["CapabilityStatus"];
        };
        /**
         * CapabilityStatus
         * @enum {string}
         */
        CapabilityStatus: "unsupported" | "not_approved" | "not_configured" | "blocked_configuration" | "manual_activation_required" | "partial" | "available";
        /** CommunitySummary */
        CommunitySummary: {
            /** Answered Comments */
            answered_comments: number;
            /** Comment Likes */
            comment_likes: number;
            data_status: components["schemas"]["DataStatus"];
            /** Top Commenters */
            top_commenters: components["schemas"]["DashboardTopCommenter"][];
            /** Top Liked Comments */
            top_liked_comments: components["schemas"]["DashboardTopLikedComment"][];
            /** Total Comments */
            total_comments: number;
            /** Unanswered Comments */
            unanswered_comments: number;
        };
        /** ConnectionsResponse */
        ConnectionsResponse: {
            /** Items */
            items: components["schemas"]["ReportingConnection"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** DashboardAudienceCapabilities */
        DashboardAudienceCapabilities: {
            activity: components["schemas"]["AvailabilityStatus"];
            age_gender: components["schemas"]["AvailabilityStatus"];
            geo: components["schemas"]["AvailabilityStatus"];
            /** Source */
            source: string | null;
        };
        /** DashboardBreakdown */
        DashboardBreakdown: {
            /** Dimension */
            dimension: string;
            /** Items */
            items: components["schemas"]["DashboardBreakdownItem"][];
            metric_id: components["schemas"]["MetricId"];
        };
        /** DashboardBreakdownItem */
        DashboardBreakdownItem: {
            /** Key */
            key: string;
            /** Percentage */
            percentage: number | null;
            /** Value */
            value: number;
        };
        /** DashboardContent */
        DashboardContent: {
            /** Account Id */
            account_id: number;
            /** Average Time Watched */
            average_time_watched: number | null;
            /** Comments Count */
            comments_count: number;
            /** Content Type */
            content_type: string;
            /** Cover Candidates */
            cover_candidates: string[];
            /** Cover Url */
            cover_url: string | null;
            data_status: components["schemas"]["DataStatus"];
            /** External Content Id */
            external_content_id: string;
            /** Full Video Watched Rate */
            full_video_watched_rate: number | null;
            /** Interactions */
            interactions: number;
            /** Likes Count */
            likes_count: number;
            /** Media Url */
            media_url: string;
            /** Media Url Candidates */
            media_url_candidates: string[];
            /** Message */
            message: string;
            /** Permalink */
            permalink: string;
            /** Published At */
            published_at: string | null;
            /** Reach */
            reach: number | null;
            /** Shares Count */
            shares_count: number;
            /** Thumbnail Candidates */
            thumbnail_candidates: string[];
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Total Time Watched */
            total_time_watched: number | null;
            /** Views */
            views: number | null;
        };
        /** DashboardContentSummary */
        DashboardContentSummary: {
            /** By Type */
            by_type: components["schemas"]["DashboardNamedValue"][];
            data_status: components["schemas"]["DataStatus"];
            /** Reach By Type */
            reach_by_type: components["schemas"]["DashboardNamedValue"][];
            /** Total */
            total: number;
            /** Views By Type */
            views_by_type: components["schemas"]["DashboardNamedValue"][];
        };
        /** DashboardHashtag */
        DashboardHashtag: {
            /** Count */
            count: number;
            /** Name */
            name: string;
        };
        /** DashboardMeta */
        DashboardMeta: {
            /** Dashboard Id */
            dashboard_id: string;
            data_status: components["schemas"]["DataStatus"];
            date_range: components["schemas"]["ReportingRange"];
            /** Expected Days */
            expected_days: number;
            freshness: components["schemas"]["FreshnessStatus"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Observed Days */
            observed_days: number;
            platform: components["schemas"]["PlatformId"] | null;
            /** Requested Brand Id */
            requested_brand_id: string;
            /** Resolved Account Ids */
            resolved_account_ids: number[];
            /** Resolved Brand Ids */
            resolved_brand_ids: string[];
            /** Rollup */
            rollup: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** DashboardMetric */
        DashboardMetric: {
            /** Availability Reason */
            availability_reason: string | null;
            data_status: components["schemas"]["DataStatus"];
            /** Delta Pct */
            delta_pct: number | null;
            /** Methodology */
            methodology: string;
            metric_id: components["schemas"]["MetricId"];
            /** Previous Value */
            previous_value: number | null;
            semantic_type: components["schemas"]["SemanticType"];
            unit: components["schemas"]["Unit"];
            /** Value */
            value: number | null;
        };
        /** DashboardMetricMethodology */
        DashboardMetricMethodology: {
            /** Engagement Rate */
            engagement_rate: string;
            /** Follower Flow */
            follower_flow: string;
            /** Reach */
            reach: string;
        };
        /** DashboardNamedValue */
        DashboardNamedValue: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** DashboardPoint */
        DashboardPoint: {
            /**
             * Observed On
             * Format: date
             */
            observed_on: string;
            /** Value */
            value: number;
        };
        /** DashboardSeries */
        DashboardSeries: {
            /** Methodology */
            methodology: string;
            metric_id: components["schemas"]["MetricId"];
            /** Points */
            points: components["schemas"]["DashboardPoint"][];
            semantic_type: components["schemas"]["SemanticType"];
        };
        /** DashboardSourceBreakdown */
        DashboardSourceBreakdown: {
            data_status: components["schemas"]["DataStatus"];
            /** Organic Only */
            organic_only: boolean;
            /** Paid Available */
            paid_available: boolean;
            reach: components["schemas"]["DashboardSourceValues"] | null;
            views: components["schemas"]["DashboardSourceValues"] | null;
        };
        /** DashboardSourceValues */
        DashboardSourceValues: {
            data_status: components["schemas"]["DataStatus"];
            /** Organic */
            organic: number | null;
            /** Paid */
            paid: number | null;
        };
        /** DashboardStories */
        DashboardStories: {
            actions: components["schemas"]["DashboardStoryActions"];
            data_status: components["schemas"]["DataStatus"];
            /** Items */
            items: components["schemas"]["DashboardStoryItem"][];
            navigation: components["schemas"]["DashboardStoryNavigation"];
            previous_summary: components["schemas"]["DashboardStorySummary"];
            summary: components["schemas"]["DashboardStorySummary"];
            trend: components["schemas"]["DashboardStoryTrend"];
        };
        /** DashboardStoryActions */
        DashboardStoryActions: {
            data_status: components["schemas"]["DataStatus"];
            /** Follows */
            follows: number | null;
            /** Profile Visits */
            profile_visits: number | null;
            /** Replies */
            replies: number | null;
            /** Saves */
            saves: number | null;
            /** Shares */
            shares: number | null;
            /** Sticker Taps */
            sticker_taps: number | null;
        };
        /** DashboardStoryItem */
        DashboardStoryItem: {
            /** Completion Rate */
            completion_rate: number | null;
            /** Content Id */
            content_id: string;
            /** Cover Url */
            cover_url: string;
            /** Created Time */
            created_time: string | null;
            data_status: components["schemas"]["DataStatus"];
            /** Exits */
            exits: number | null;
            /** Follows */
            follows: number | null;
            /** Interactions */
            interactions: number | null;
            /** Navigation */
            navigation: number | null;
            /** Permalink */
            permalink: string;
            /** Profile Visits */
            profile_visits: number | null;
            /** Reach */
            reach: number | null;
            /** Replies */
            replies: number | null;
            /** Saves */
            saves: number | null;
            /** Shares */
            shares: number | null;
            /** Sticker Taps */
            sticker_taps: number | null;
            /** Swipe Forward */
            swipe_forward: number | null;
            /** Taps Back */
            taps_back: number | null;
            /** Taps Forward */
            taps_forward: number | null;
            /** Title */
            title: string;
            /** Views */
            views: number | null;
        };
        /** DashboardStoryNavigation */
        DashboardStoryNavigation: {
            data_status: components["schemas"]["DataStatus"];
            /** Exits */
            exits: number | null;
            /** Swipe Forward */
            swipe_forward: number | null;
            /** Taps Back */
            taps_back: number | null;
            /** Taps Forward */
            taps_forward: number | null;
        };
        /** DashboardStorySummary */
        DashboardStorySummary: {
            /** Completion Rate */
            completion_rate: number | null;
            /** Count */
            count: number;
            data_status: components["schemas"]["DataStatus"];
            /** Interactions */
            interactions: number | null;
            /** Reach */
            reach: number | null;
            /** Replies */
            replies: number | null;
            /** Views */
            views: number | null;
        };
        /** DashboardStoryTrend */
        DashboardStoryTrend: {
            data_status: components["schemas"]["DataStatus"];
            /** Labels */
            labels: string[];
            /** Reach */
            reach: (number | null)[];
            /** Views */
            views: (number | null)[];
        };
        /** DashboardTopCommenter */
        DashboardTopCommenter: {
            /** Comments */
            comments: number;
            /** Likes */
            likes: number;
            /** Name */
            name: string;
        };
        /** DashboardTopLikedComment */
        DashboardTopLikedComment: {
            /** Comment */
            comment: string;
            /** Likes */
            likes: number;
            /** Name */
            name: string;
            /** Replies */
            replies: number;
        };
        /**
         * DataStatus
         * @enum {string}
         */
        DataStatus: "available" | "partial" | "unavailable";
        /**
         * FreshnessStatus
         * @enum {string}
         */
        FreshnessStatus: "fresh" | "stale" | "outdated" | "never_synced";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Items */
            items: components["schemas"]["ReportingInsight"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** MetaAccountSelectionPayload */
        MetaAccountSelectionPayload: {
            /** External Id */
            external_id: string;
            platform: components["schemas"]["PlatformId"];
        };
        /** MetaDiscoveryItem */
        MetaDiscoveryItem: {
            /** Connection Id */
            connection_id: number;
            /** Display Name */
            display_name: string;
            /** External Id */
            external_id: string;
            platform: components["schemas"]["PlatformId"];
            /** Status */
            status: string;
        };
        /** MetaLinkPayload */
        MetaLinkPayload: {
            /** Accounts */
            accounts: components["schemas"]["MetaAccountSelectionPayload"][];
            /** Connection Id */
            connection_id: number;
        };
        /** MetaLinkResponse */
        MetaLinkResponse: {
            /** Connection Id */
            connection_id: number;
            /** Connection State */
            connection_state: string;
            /** Linked Count */
            linked_count: number;
        };
        /** MetaSelfServiceReadinessResponse */
        MetaSelfServiceReadinessResponse: {
            /** Brand Id */
            brand_id: string;
            /** Can Manage */
            can_manage: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Connection State */
            connection_state: string;
            /** Discoveries */
            discoveries: components["schemas"]["MetaDiscoveryItem"][];
            /** Facebook Linked Count */
            facebook_linked_count: number;
            /** Instagram Linked Count */
            instagram_linked_count: number;
            /** Oauth Start Available */
            oauth_start_available: boolean;
            /** Reason */
            reason: string;
            runtime_mode: components["schemas"]["RuntimeMode"];
            /** Writes Enabled */
            writes_enabled: boolean;
        };
        /** MetaSelfServiceStartResponse */
        MetaSelfServiceStartResponse: {
            /** Authorization Url */
            authorization_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * MetricId
         * @enum {string}
         */
        MetricId: "followers" | "following" | "new_followers" | "follows" | "unfollows" | "followers_net" | "reach" | "reach_paid" | "reach_organic" | "views" | "views_paid" | "views_organic" | "interactions" | "page_views" | "profile_views" | "website_clicks" | "total_actions" | "reactions" | "media_count" | "video_views_total" | "video_views_change" | "video_likes_total" | "video_comments_total" | "video_shares_total" | "video_engagements_total" | "video_engagement_rate";
        /** OperationsReadinessResponse */
        OperationsReadinessResponse: {
            /** Database Configured */
            database_configured: boolean;
            /**
             * Platforms
             * @default []
             */
            platforms: components["schemas"]["ReadinessPlatform"][];
            runtime_mode: components["schemas"]["RuntimeMode"];
            scope?: components["schemas"]["BrandScope"] | null;
            /** Status */
            status: string;
            /** Writes Enabled */
            writes_enabled: boolean;
        };
        /** OverviewDashboard */
        OverviewDashboard: {
            community: components["schemas"]["CommunitySummary"];
            /** Content */
            content: components["schemas"]["DashboardContent"][];
            meta: components["schemas"]["DashboardMeta"];
            /** Metrics */
            metrics: components["schemas"]["DashboardMetric"][];
            /** Platforms */
            platforms: components["schemas"]["PlatformDashboard"][];
        };
        /** PlatformAccountsResponse */
        PlatformAccountsResponse: {
            /** Accounts */
            accounts: components["schemas"]["ReportingAccount"][];
            meta: components["schemas"]["BrandScope"];
            platform: components["schemas"]["PlatformId"];
        };
        /** PlatformDashboard */
        PlatformDashboard: {
            audience_capabilities: components["schemas"]["DashboardAudienceCapabilities"];
            /** Breakdowns */
            breakdowns: components["schemas"]["DashboardBreakdown"][];
            community: components["schemas"]["CommunitySummary"];
            /** Content */
            content: components["schemas"]["DashboardContent"][];
            content_summary: components["schemas"]["DashboardContentSummary"];
            meta: components["schemas"]["DashboardMeta"];
            metric_methodology: components["schemas"]["DashboardMetricMethodology"];
            /** Metrics */
            metrics: components["schemas"]["DashboardMetric"][];
            /** Series */
            series: components["schemas"]["DashboardSeries"][];
            source_breakdown: components["schemas"]["DashboardSourceBreakdown"] | null;
            stories: components["schemas"]["DashboardStories"] | null;
            /** Top Hashtags */
            top_hashtags: components["schemas"]["DashboardHashtag"][];
        };
        /**
         * PlatformId
         * @enum {string}
         */
        PlatformId: "facebook" | "instagram" | "tiktok";
        /** ReadinessPlatform */
        ReadinessPlatform: {
            /** Account Count */
            account_count: number;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Pending Job Count */
            pending_job_count: number;
            platform: components["schemas"]["PlatformId"];
        };
        /** ReportingAccount */
        ReportingAccount: {
            /** Account Id */
            account_id: number;
            /** Backfill Status */
            backfill_status: string;
            /** Brand Id */
            brand_id: string;
            /** Connection State */
            connection_state: string;
            /** Display Name */
            display_name: string;
            /** External Id */
            external_id: string;
            /** Health Status */
            health_status: string;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Nightly Enabled */
            nightly_enabled: boolean;
            platform: components["schemas"]["PlatformId"];
            /** Status */
            status: string;
        };
        /** ReportingConnection */
        ReportingConnection: {
            /** Brand Id */
            brand_id: string;
            /** Connection Id */
            connection_id: number;
            /** Expires At */
            expires_at: string | null;
            platform: components["schemas"]["PlatformId"];
            /** Projected At */
            projected_at: string | null;
            /** State */
            state: string;
        };
        /** ReportingInsight */
        ReportingInsight: {
            /** Brand Id */
            brand_id: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Insight Id */
            insight_id: number;
            /** Recommendations */
            recommendations: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary: string | null;
        };
        /** ReportingRange */
        ReportingRange: {
            /**
             * End On
             * Format: date
             */
            end_on: string;
            /** Key */
            key: string;
            /**
             * Start On
             * Format: date
             */
            start_on: string;
        };
        /** ReportingSyncJob */
        ReportingSyncJob: {
            /** Account Id */
            account_id: number | null;
            /** Brand Id */
            brand_id: string;
            /** Error Code */
            error_code: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Job Id */
            job_id: number;
            platform: components["schemas"]["PlatformId"];
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** RuntimeCapabilities */
        RuntimeCapabilities: {
            /** Automated Schedule Available */
            automated_schedule_available: boolean;
            mode: components["schemas"]["RuntimeMode"];
            /** Writes Enabled */
            writes_enabled: boolean;
        };
        /**
         * RuntimeMode
         * @enum {string}
         */
        RuntimeMode: "development" | "dormant" | "staging" | "standalone_ready" | "active";
        /**
         * SemanticType
         * @enum {string}
         */
        SemanticType: "snapshot" | "flow" | "cumulative" | "ratio";
        /** SettingsBrandItem */
        SettingsBrandItem: {
            /** Access Mode */
            access_mode: string | null;
            /** Brand Id */
            brand_id: string;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Linked Account Count */
            linked_account_count: number;
            /** Name */
            name: string | null;
            /** Parent Brand Id */
            parent_brand_id: string | null;
            /** Role */
            role: string | null;
            /** Visibility */
            visibility: string;
        };
        /** SettingsBrandsResponse */
        SettingsBrandsResponse: {
            /** Items */
            items: components["schemas"]["SettingsBrandItem"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** SocialAccountsResponse */
        SocialAccountsResponse: {
            /** Items */
            items: components["schemas"]["ReportingAccount"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** SyncJobsResponse */
        SyncJobsResponse: {
            /** Items */
            items: components["schemas"]["ReportingSyncJob"][];
            meta: components["schemas"]["BrandScope"];
        };
        /** TikTokActivationReadinessResponse */
        TikTokActivationReadinessResponse: {
            /** Brand Id */
            brand_id: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Connection State */
            connection_state: string;
            /**
             * Fresh Until
             * Format: date-time
             */
            fresh_until: string;
            /** Handoff Ready */
            handoff_ready: boolean;
            /** Launch Target */
            launch_target: string;
            /** Oauth Start Available */
            oauth_start_available: boolean;
            /** Reason */
            reason: string;
            runtime_mode: components["schemas"]["RuntimeMode"];
            /** Writes Enabled */
            writes_enabled: boolean;
        };
        /** TikTokConnectionResponse */
        TikTokConnectionResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityRecord"][];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            connection: components["schemas"]["ReportingConnection"] | null;
            meta: components["schemas"]["BrandScope"];
            /** State */
            state: string;
        };
        /** TikTokSelfServiceReadinessResponse */
        TikTokSelfServiceReadinessResponse: {
            /** Brand Id */
            brand_id: string;
            /** Can Manage */
            can_manage: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Connection State */
            connection_state: string;
            /** Linked Account Count */
            linked_account_count: number;
            /** Oauth Start Available */
            oauth_start_available: boolean;
            /** Reason */
            reason: string;
            runtime_mode: components["schemas"]["RuntimeMode"];
            /** Writes Enabled */
            writes_enabled: boolean;
        };
        /** TikTokSelfServiceStartResponse */
        TikTokSelfServiceStartResponse: {
            /** Authorization Url */
            authorization_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "count" | "ratio";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceBrand */
        WorkspaceBrand: {
            /** Access Mode */
            access_mode: ("read" | "write") | null;
            /** Brand Id */
            brand_id: string;
            /** Name */
            name: string | null;
            /** Parent Brand Id */
            parent_brand_id: string | null;
            /** Role */
            role: string | null;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "active" | "hidden_parent";
        };
        /** WorkspaceCapabilitiesResponse */
        WorkspaceCapabilitiesResponse: {
            permissions: components["schemas"]["WorkspacePermissions"];
            /** Platforms */
            platforms: components["schemas"]["CapabilityPlatform"][];
            runtime: components["schemas"]["RuntimeCapabilities"];
            scope: components["schemas"]["BrandScope"];
        };
        /** WorkspacePermissions */
        WorkspacePermissions: {
            /** Integrations Visible */
            integrations_visible: boolean;
            /** Internal Audit Visible */
            internal_audit_visible: boolean;
            /** Meta Connection Manage */
            meta_connection_manage: boolean;
            /** Operation Mutation Available */
            operation_mutation_available: boolean;
            /** Rollup Available */
            rollup_available: boolean;
            /** Settings Visible */
            settings_visible: boolean;
            /** Tiktok Connection Manage */
            tiktok_connection_manage: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_dashboards_facebook_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                range?: string;
                start_date?: string | null;
                end_date?: string | null;
                account_id?: number | null;
                content_type?: string | null;
                tab?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_dashboards_instagram_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                range?: string;
                start_date?: string | null;
                end_date?: string | null;
                account_id?: number | null;
                content_type?: string | null;
                tab?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_dashboards_overview_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                range?: string;
                start_date?: string | null;
                end_date?: string | null;
                content_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_dashboards_tiktok_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                range?: string;
                start_date?: string | null;
                end_date?: string | null;
                account_id?: number | null;
                content_type?: string | null;
                tab?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    insights_api_insights_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_link_accounts_api_integrations_meta_accounts_link_post: {
        parameters: {
            query: {
                brand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetaLinkPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_self_service_start_api_integrations_meta_oauth_start_post: {
        parameters: {
            query: {
                brand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaSelfServiceStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_self_service_readiness_api_integrations_meta_self_service_readiness_get: {
        parameters: {
            query: {
                brand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaSelfServiceReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integration_connections_api_integrations_status_connections_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integration_social_accounts_api_integrations_status_social_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                platform?: components["schemas"]["PlatformId"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integration_sync_jobs_api_integrations_status_sync_jobs_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiktok_self_service_start_api_integrations_tiktok_oauth_start_post: {
        parameters: {
            query: {
                brand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TikTokSelfServiceStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiktok_self_service_readiness_api_integrations_tiktok_self_service_readiness_get: {
        parameters: {
            query: {
                brand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TikTokSelfServiceReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_media_api_media__platform___content_id__get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                account_id?: number | null;
            };
            header?: never;
            path: {
                platform: components["schemas"]["PlatformId"];
                content_id: string;
            };
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backfill_api_operations_backfill_post: {
        parameters: {
            query: {
                platform: components["schemas"]["PlatformId"];
                account_id: number;
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Successful Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_api_operations_readiness_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_operations_sync_post: {
        parameters: {
            query: {
                platform: components["schemas"]["PlatformId"];
                account_id: number;
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Successful Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    endpoint_api_platforms_facebook_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_platforms_instagram_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_platforms_tiktok_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_settings_audit_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brand_links_api_settings_brand_links_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandLinksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brands_api_settings_brands_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBrandsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connections_api_settings_connections_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    social_accounts_api_settings_social_accounts_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
                platform?: components["schemas"]["PlatformId"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialAccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_jobs_api_settings_sync_jobs_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiktok_activation_readiness_api_settings_tiktok_activation_readiness_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TikTokActivationReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiktok_connection_api_settings_tiktok_connection_get: {
        parameters: {
            query?: {
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TikTokConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tiktok_connection_api_settings_tiktok_connection_delete: {
        parameters: {
            query?: {
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Successful Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    tiktok_activation_start_api_settings_tiktok_oauth_account_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_activation_callback_api_social_meta_oauth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiktok_activation_callback_api_social_tiktok_oauth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_brands_api_workspace_brands_get: {
        parameters: {
            query?: {
                selected_brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandWorkspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_capabilities_api_workspace_capabilities_get: {
        parameters: {
            query?: {
                selected_brand_id?: string | null;
                rollup?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                social_media_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceCapabilitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
