"""Local SQLAlchemy registry for the V2-owned social data surface."""

from __future__ import annotations

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)

metadata = MetaData()

metric_rows = Table(
    "metrics_daily",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True, nullable=False),
    Column("asset_id", Integer, ForeignKey("assets.id"), nullable=False),
    Column("brand_id", Integer, ForeignKey("brands.id"), nullable=False),
    Column("date", Date, primary_key=True, nullable=False),
    Column("metric_id", String(64), nullable=False),
    Column("value_numeric", Float, nullable=False),
    Column("breakdown_key", String(64), nullable=True),
    Column("breakdown_value", String(128), nullable=True),
    UniqueConstraint(
        "asset_id",
        "date",
        "metric_id",
        "breakdown_key",
        "breakdown_value",
        name="uq_metrics_daily_key",
    ),
)
Index(
    "uq_metrics_daily_account_rows",
    metric_rows.c.asset_id,
    metric_rows.c.date,
    metric_rows.c.metric_id,
    unique=True,
    postgresql_where=text("breakdown_key IS NULL AND breakdown_value IS NULL"),
)
Index(
    "uq_metrics_daily_breakdown_rows",
    metric_rows.c.asset_id,
    metric_rows.c.date,
    metric_rows.c.metric_id,
    metric_rows.c.breakdown_key,
    metric_rows.c.breakdown_value,
    unique=True,
    postgresql_where=text("breakdown_key IS NOT NULL AND breakdown_value IS NOT NULL"),
)

content_rows = Table(
    "content_items",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("asset_id", Integer, ForeignKey("assets.id"), nullable=False),
    Column("brand_id", Integer, ForeignKey("brands.id"), nullable=False),
    Column("content_id", String(128), nullable=False),
    Column("content_type", String(32), nullable=False),
    Column("permalink", String(512), nullable=False),
    Column("message", String(4096), nullable=False),
    Column("media_url", String(2048), nullable=False),
    Column("created_time", DateTime(timezone=True), nullable=True),
    Column("likes_count", Integer, nullable=True),
    Column("comments_count", Integer, nullable=True),
    Column("shares_count", Integer, nullable=True),
    Column("views_count", Float, nullable=True),
    Column("reach_count", Float, nullable=True),
    Column("cover_url", String(2048), nullable=True),
    Column("thumbnail_url", String(2048), nullable=True),
    Column("cover_candidates", JSON, nullable=False),
    Column("thumbnail_candidates", JSON, nullable=False),
    Column("media_url_candidates", JSON, nullable=False),
    Column("full_video_watched_rate", Float, nullable=True),
    Column("total_time_watched", Float, nullable=True),
    Column("average_time_watched", Float, nullable=True),
    Column("interactions_count", Float, nullable=True),
    Column("replies_count", Float, nullable=True),
    Column("saves_count", Float, nullable=True),
    Column("sticker_taps", Float, nullable=True),
    Column("profile_visits", Float, nullable=True),
    Column("follows_count", Float, nullable=True),
    Column("taps_forward", Float, nullable=True),
    Column("taps_back", Float, nullable=True),
    Column("swipe_forward", Float, nullable=True),
    Column("exits", Float, nullable=True),
    Column("navigation_count", Float, nullable=True),
    Column("completion_rate", Float, nullable=True),
    Column("reposts_count", Integer, nullable=True),
    Column("quotes_count", Integer, nullable=True),
    Column("clicks_count", Integer, nullable=True),
    Column("link_clicks", Integer, nullable=True),
    Column("profile_clicks", Integer, nullable=True),
    Column("video_views_count", Integer, nullable=True),
    Column("video_playback_0_count", Integer, nullable=True),
    Column("video_playback_25_count", Integer, nullable=True),
    Column("video_playback_50_count", Integer, nullable=True),
    Column("video_playback_75_count", Integer, nullable=True),
    Column("video_playback_100_count", Integer, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("asset_id", "content_id", name="uq_content_items_asset_content"),
)

comment_rows = Table(
    "content_comments",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("asset_id", Integer, ForeignKey("assets.id"), nullable=False),
    Column("content_id", String(255), nullable=False),
    Column("platform", String(32), nullable=False),
    Column("comment_id", String(255), nullable=False),
    Column("user_id", String(255), nullable=True),
    Column("user_name", String(255), nullable=True),
    Column("text", Text, nullable=False),
    Column("like_count", Integer, nullable=False),
    Column("reply_count", Integer, nullable=False),
    Column("answered", Boolean, nullable=False),
    Column("attachment_type", String(64), nullable=True),
    Column("attachment_media_type", String(64), nullable=True),
    Column("attachment_url", String(1024), nullable=True),
    Column("commented_at", DateTime(timezone=True), nullable=True),
    Column("sentiment", String(16), nullable=True),
    Column("sentiment_model", String(128), nullable=True),
    Column("sentiment_classified_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("asset_id", "comment_id", name="uq_content_comments_asset_comment"),
)

media_rows = Table(
    "media_assets",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("brand_id", Integer, ForeignKey("brands.id"), nullable=False),
    Column("asset_id", Integer, ForeignKey("assets.id"), nullable=False),
    Column("content_id", String(128), nullable=False),
    Column("platform", String(32), nullable=False),
    Column("media_kind", String(32), nullable=False),
    Column("storage_path", String(1024), nullable=False),
    Column("source_url", String(2048), nullable=False),
    Column("source_status", Integer, nullable=True),
    Column("mime_type", String(128), nullable=False),
    Column("size_bytes", Integer, nullable=False),
    Column("checksum", String(64), nullable=False),
    Column("last_verified_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint(
        "asset_id",
        "content_id",
        "media_kind",
        name="uq_media_assets_asset_content_kind",
    ),
)

REGISTERED_TABLES = (metric_rows, content_rows, comment_rows, media_rows)

__all__ = ["REGISTERED_TABLES", "metadata"]
