"""Canonical application ports."""

from typing import Protocol

from .ai_summary import (
    AiSummaryError,
    AiSummaryLimitStatus,
    AiSummaryOutput,
    AiSummaryProvider,
    AiSummaryRepository,
    AiSummaryService,
)
from .comment_sentiment import (
    ClassifiedCommentSentiment,
    CommentSentimentBatch,
    CommentSentimentProvider,
    CommentSentimentRepository,
    PendingCommentSentiment,
)
from .meta_activation import (
    MetaActivationError,
    MetaActivationProvider,
    MetaCatalogAccount,
    MetaConnectionResult,
    MetaConnectionStore,
    MetaCredentialBinding,
    MetaDiscovery,
    MetaLinkResult,
    MetaLinkSelection,
    MetaProviderAccount,
    MetaProviderGrant,
    MetaRefreshConnection,
)
from .oauth_channels import (
    OAUTH_CHANNEL_PLATFORMS,
    OAuthAccountGrant,
    OAuthChannelError,
    OAuthChannelProvider,
    OAuthConnectionResult,
    OAuthConnectionStore,
    OAuthCredentialBinding,
    OAuthDiscovery,
    OAuthLinkResult,
    OAuthLinkSelection,
    OAuthProviderGrant,
)
from .reporting import ReportingStore
from .session_store import SessionStore
from .tiktok_activation import (
    ActivationAuthority,
    ActivationContext,
    ActivationIntent,
    ActivationIntentStore,
    ActivationLink,
    ActivationLinkStore,
    ActivationResult,
    ActivationStart,
    ActivationStateClaims,
    ActivationStatePort,
    OAuthActivationStatePort,
    ProviderAccountGrant,
    ProviderPayloadTransport,
    ProviderTokenGrant,
    TikTokActivationError,
    TikTokActivationProvider,
    TikTokActivationStatePort,
)


class AuthorityStore(SessionStore, Protocol):
    """V2-owned local session store used by the SSO boundary."""


__all__ = [
    "AiSummaryError",
    "AiSummaryLimitStatus",
    "AiSummaryOutput",
    "AiSummaryProvider",
    "AiSummaryRepository",
    "AiSummaryService",
    "AuthorityStore",
    "ClassifiedCommentSentiment",
    "CommentSentimentBatch",
    "CommentSentimentProvider",
    "CommentSentimentRepository",
    "ActivationAuthority",
    "ActivationContext",
    "ActivationIntent",
    "ActivationIntentStore",
    "ActivationLink",
    "ActivationLinkStore",
    "ActivationResult",
    "ActivationStart",
    "ActivationStateClaims",
    "ActivationStatePort",
    "OAuthActivationStatePort",
    "TikTokActivationStatePort",
    "MetaActivationError",
    "MetaActivationProvider",
    "MetaCatalogAccount",
    "MetaConnectionResult",
    "MetaConnectionStore",
    "MetaCredentialBinding",
    "MetaDiscovery",
    "MetaLinkResult",
    "MetaLinkSelection",
    "MetaProviderAccount",
    "MetaProviderGrant",
    "MetaRefreshConnection",
    "OAUTH_CHANNEL_PLATFORMS",
    "OAuthAccountGrant",
    "OAuthChannelError",
    "OAuthChannelProvider",
    "OAuthConnectionResult",
    "OAuthConnectionStore",
    "OAuthCredentialBinding",
    "OAuthDiscovery",
    "OAuthLinkResult",
    "OAuthLinkSelection",
    "OAuthProviderGrant",
    "PendingCommentSentiment",
    "ReportingStore",
    "SessionStore",
    "ProviderAccountGrant",
    "ProviderPayloadTransport",
    "ProviderTokenGrant",
    "TikTokActivationError",
    "TikTokActivationProvider",
]
